"""Create urlbase table

Revision ID: d9c2bec15a07
Revises: 
Create Date: 2024-10-29 10:26:07.318435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c2bec15a07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urlbase',
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('short_url')
    )
    op.create_index(op.f('ix_urlbase_original_url'), 'urlbase', ['original_url'], unique=False)
    op.create_index(op.f('ix_urlbase_short_url'), 'urlbase', ['short_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_urlbase_short_url'), table_name='urlbase')
    op.drop_index(op.f('ix_urlbase_original_url'), table_name='urlbase')
    op.drop_table('urlbase')
    # ### end Alembic commands ###
